CREATE OR REPLACE PROCEDURE CHECK_SUM(CL_ID IN NUMBER, TOTAL IN OUT NUMBER)
IS
    TEMP NUMBER;
    
    CURSOR ROOMS IS
    SELECT PRICE 
    FROM "CHECK"
    INNER JOIN ROOM ON "CHECK".ROOM_ID = ROOM.ID
    WHERE "CHECK".CLIENT_ID = CL_ID;
    
    CURSOR SERVICES IS 
    SELECT PRICE  
    FROM SERVICE_CHECK
    INNER JOIN "CHECK" ON SERVICE_CHECK.CHECK_ID = "CHECK".ID
    INNER  JOIN SERVICE ON SERVICE_CHECK.SERVICE_ID = SERVICE.ID
    WHERE "CHECK".CLIENT_ID = CL_ID;
BEGIN
    FOR ROOM IN ROOMS
    LOOP
        DBMS_OUTPUT.PUT_LINE('CLIENT WITH ID ' || CL_ID || ' BOOKED A ROOMS WITH PRICE ' || ROOM.PRICE);
        TOTAL := TOTAL + ROOM.PRICE;
    END LOOP;
    
    FOR SERVICE IN SERVICES
    LOOP
        DBMS_OUTPUT.PUT_LINE('CLIENT WITH ID ' || CL_ID || ' BOOKED A SERVICE WITH PRICE ' || SERVICE.PRICE);
        TOTAL := TOTAL + SERVICE.PRICE;
    END LOOP;
END CHECK_SUM;
/

DECLARE
    CLIENT_ID NUMBER := 1;
    TOTAL_SUM NUMBER := 0;
BEGIN
    CHECK_SUM(CLIENT_ID, TOTAL=>TOTAL_SUM);
    DBMS_OUTPUT.PUT_LINE('TOTAL AMOUNT OF MONEY CLIENT ' || CLIENT_ID || ' HAS TO PAY = ' || TOTAL_SUM);
END;
/