CREATE OR REPLACE PROCEDURE NAME_UPPER
IS
BEGIN
    UPDATE CLIENT
    SET NAME = UPPER(NAME);
END NAME_UPPER;
/

EXECUTE NAME_UPPER;

CREATE OR REPLACE PROCEDURE NAME_LOWER
IS
BEGIN
    UPDATE CLIENT
    SET NAME = LOWER(NAME);
END NAME_LOWER;
/

EXECUTE NAME_LOWER;