CREATE OR REPLACE FUNCTION PERIOD(CHECK_IN IN DATE, CHECK_OUT IN DATE)
RETURN NUMBER 
IS
    NUM_OF_DAYS NUMBER;
BEGIN
    NUM_OF_DAYS := CHECK_OUT - CHECK_IN;
    RETURN NUM_OF_DAYS;
END PERIOD;
/

SELECT NAME, PERIOD(CHECK_IN, CHECK_OUT) AS PERIOD
FROM "CHECK"
INNER JOIN CLIENT ON "CHECK".CLIENT_ID  = CLIENT.ID;
