CREATE TRIGGER ROOM_SECURITY
BEFORE DELETE OR INSERT
ON ROOM
BEGIN
    IF DELETING THEN
        RAISE_APPLICATION_ERROR(-20000, 'ROOMS CANNOT BE DELETED! ONLY UPDATED!');
    ELSIF INSERTING THEN
        RAISE_APPLICATION_ERROR(-20001, 'ROOMS CANNOT BE INSERTED! ONLY UPDATED!');
    END IF;
END ROOM_SECURITY;
/

INSERT INTO ROOM 
VALUES(10, 1000, 2, 'high');

DELETE FROM ROOM
WHERE ID = 1;

CREATE TRIGGER PARTY_ROOM_CAPACITY
BEFORE UPDATE 
ON ROOM
FOR EACH ROW
WHEN (NEW.COMFORT = 'party')
BEGIN
    IF :NEW.CAPACITY < 10 THEN
        :NEW.CAPACITY := 10;
    END IF;
END PARTY_ROOM_CAPACITY;
/

UPDATE ROOM
SET CAPACITY = 5
WHERE COMFORT = 'party';

ALTER TRIGGER PARTY_ROOM_CAPACITY DISABLE;
ALTER TRIGGER PARTY_ROOM_CAPACITY ENABLE;
DROP TRIGGER PARTY_ROOM_CAPACITY;