--1
CREATE OR REPLACE FORCE VIEW "1"("COMFORT", "TOTAL_INCOME") AS
SELECT COMFORT, SUM(PRICE)
FROM ROOM
GROUP BY COMFORT;

--2
CREATE OR REPLACE FORCE VIEW "2"("COMFORT", "TOTAL_INCOME", "NUMBER_OF_ROOMS") AS
SELECT COMFORT, SUM(PRICE), COUNT(ID)
FROM ROOM
GROUP BY COMFORT
HAVING COUNT(ID) > 1;

--3
CREATE TABLE PAYMENT AS
(
    SELECT "CLIENT".NAME, "ROOM".ID, "ROOM".PRICE
    FROM "CLIENT" INNER JOIN "CHECK" ON "CHECK".CLIENT_ID = "CLIENT".ID
    INNER JOIN "ROOM" ON "CHECK".ROOM_ID = "ROOM".ID
    WHERE "ROOM".PRICE > 300
);

--4
UPDATE ROOM_
SET PRICE = PRICE * 1.5;

--5
DELETE 
FROM PENTHOUSE
WHERE PRICE > 20000;

--6
CREATE SEQUENCE SEQ;

CREATE TABLE "ROOM_COPY"(
"ID" NUMBER NOT NULL ENABLE,
"PRICE" NUMBER NOT  NULL ENABLE,
"CAPACITY" NUMBER NOT NULL ENABLE,
"COMFORT" CHAR(20) NOT NULL ENABLE,
CONSTRAINT "ROOM_COPY_PK" PRIMARY KEY ("ID") ENABLE
);

INSERT INTO "ROOM_COPY"
SELECT SEQ.NEXTVAL, "PRICE", "CAPACITY", "COMFORT"
FROM "ROOM"
WHERE "PRICE" > 350;