CREATE OR REPLACE PROCEDURE AUTO_FILL
IS
BEGIN
    FOR I IN 1..30
    LOOP
        INSERT INTO INVOICE
        VALUES(INVOICE_SEQ.NEXTVAL, RANDOM_NUM(1,2), RANDOM_NUM(1,4), RANDOM_NUM(1,7), RANDOM_NUM(1,3), 
        RANDOM_NUM(1,2), RANDOM_NUM(1,3), I+20, RANDOM_NUM(1,10), TO_DATE('01-01-2016', 'DD-MM-YY')+RANDOM_NUM(0, 1500));
    END LOOP;
END AUTO_FILL;

CREATE OR REPLACE FUNCTION RANDOM_NUM(LOW_BORDER IN NUMBER, HIGH_BORDER IN NUMBER)
RETURN NUMBER IS
BEGIN
    RETURN ROUND(DBMS_RANDOM.VALUE(LOW_BORDER, HIGH_BORDER));
END RANDOM_NUM;

EXECUTE AUTO_FILL;