BEGIN
    INSERT INTO ROOM
    VALUES(9, 1000, 2, 'high');
    SAVEPOINT SP1;
    INSERT INTO ROOM
    VALUES(10, 1500, 3, 'high');
    SAVEPOINT SP2;
    INSERT INTO ROOM
    VALUES(11, 5000, 10, 'party');
    SAVEPOINT SP3;
    ROLLBACK TO SP1;
    COMMIT;
END;

SET TRANSACTION READ ONLY;
INSERT INTO ROOM
VALUES(10, 1500, 3, 'high');
ROLLBACK;

SELECT OWNER, OBJECT_NAME FROM V$SEGMENT_STATISTICS
WHERE STATISTIC_NAME = 'ITL waits' AND VALUE > 0;