--1
SELECT CAR_MODEL, MANUFACTURE_DATE, STORAGE_DATE
FROM CAR
WHERE TO_DATE('27-7-16', 'DD-MM-YY') BETWEEN MANUFACTURE_DATE AND STORAGE_DATE
ORDER BY CAR_MODEL, STORAGE_DATE;

--2
SELECT LAST_NAME AS NAME,
COUNT(*) AS QUANTITY_OF_ORDERS
FROM MANAGER
INNER JOIN PURCHASE ON MANAGER.ID = MANAGER_ID
GROUP BY LAST_NAME
HAVING COUNT(*) = 
(
    SELECT MAX(COUNT(*))
    FROM PURCHASE
    GROUP BY MANAGER_ID
);

--3
SELECT LAST_NAME AS NAME
FROM MANAGER
WHERE LAST_NAME NOT IN
(
    SELECT LAST_NAME
    FROM MANAGER INNER JOIN PURCHASE ON MANAGER_ID = MANAGER.ID
);

--4
SELECT LAST_NAME, FIRST_NAME, CAR_MODEL
FROM CUSTOMER 
INNER JOIN PURCHASE ON CUSTOMER_ID = CUSTOMER.ID
WHERE CAR_MODEL IN
(
  SELECT CAR_MODEL
  FROM PURCHASE
  GROUP BY CAR_MODEL
  HAVING COUNT(*) = 1
); 

--5
SELECT COUNT(*)
FROM CAR
WHERE CURRENT_DATE - STORAGE_DATE > 30; 
