--1
CREATE OR REPLACE FORCE VIEW  "SORT"("ID", "NAME", "PASSPORT", "PHONE_NUMBER") AS 
SELECT *
FROM "CLIENT"
ORDER BY "NAME";

--2.1
CREATE OR REPLACE FORCE VIEW  "LOGIC"("ID", "NAME", "PRICE") AS 
SELECT *
FROM SERVICE
WHERE PRICE > 50
ORDER BY NAME DESC;

--2.2
CREATE OR REPLACE FORCE VIEW  "LOGIC2"("ID", "DATE", "CHECK_IN", "CHECK_OUT", "CLIENT_ID", "ROOM_ID") AS 
SELECT *
FROM CHECK_
WHERE CLIENT_ID < 6 AND "DATE" IS NOT NULL;

--3.1
CREATE OR REPLACE FORCE VIEW  "SUBQUERY"("ID", "NAME", "PASSPORT", "PHONE_NUMBER") AS 
SELECT * 
FROM "CLIENT"
WHERE EXISTS 
(
    SELECT *
    FROM "CHECK"
    WHERE "CLIENT".ID = "CHECK".CLIENT_ID
);

--3.2
CREATE OR REPLACE FORCE VIEW  "SUBQUERY2"("ID", "PRICE", "CAPACITY", "COMFORT") AS 
SELECT * 
FROM ROOM
WHERE COMFORT IN ('low', 'medium');

--3.3
CREATE OR REPLACE FORCE VIEW  "SUBQUERY3"("ID", "PRICE", "CAPACITY", "COMFORT") AS 
SELECT * 
FROM (SELECT * FROM ROOM WHERE COMFORT = 'high')
WHERE CAPACITY = 2;

--4.1.1
CREATE OR REPLACE FORCE VIEW "INNER_JOIN"("NAME", "CHECK_NUMBER") AS
SELECT "CLIENT".NAME, "CHECK".ID
FROM "CLIENT"
INNER JOIN "CHECK" ON "CLIENT".ID = "CHECK".CLIENT_ID;

--4.1.2
CREATE OR REPLACE FORCE VIEW "INNER_JOIN2"("NAME", "ROOM_NUMBER") AS
SELECT "CLIENT".NAME, "ROOM".ID
FROM "CLIENT"
INNER JOIN "CHECK" ON "CLIENT".ID = "CHECK".CLIENT_ID
INNER JOIN "ROOM" ON "CHECK".ROOM_ID = "ROOM".ID;

--4.2
CREATE OR REPLACE FORCE VIEW "LEFT_JOIN"("NAME", "CHECK_NUMBER") AS
SELECT "CLIENT".NAME, "CHECK".ID
FROM "CLIENT"
LEFT OUTER JOIN "CHECK" ON "CLIENT".ID = "CHECK".CLIENT_ID;

--4.3
CREATE OR REPLACE FORCE VIEW "RIGTH_JOIN"("CHECK_NUMBER", "ROOM_NUMBER") AS
SELECT "CHECK".ID, "ROOM".ID
FROM "CHECK"
RIGHT OUTER JOIN "ROOM" ON "CHECK".ROOM_ID = "ROOM".ID;

--5
CREATE OR REPLACE FORCE VIEW "UNION"("ID", "PRICE", "CAPACITY") AS
SELECT ID, PRICE, CAPACITY
FROM "ROOM"
UNION
SELECT ID, PRICE, CAPACITY
FROM "PENTHOUSE";

--6.1
CREATE OR REPLACE FORCE VIEW "6.1"("DATE", "STRING") AS
SELECT "DATE", TO_CHAR("CHECK_"."DATE")
FROM "CHECK_"
WHERE "DATE" IS NOT NULL;

--6.2
CREATE OR REPLACE FORCE VIEW "6.2"("NAME") AS
SELECT "NAME"
FROM "CLIENT"
WHERE "NAME" LIKE 'R%';

--6.3
UPDATE "CHECK_"
SET "DATE" = TO_DATE('26-03-18','DD-MM-YY')
WHERE "DATE" IS NULL;

CREATE OR REPLACE FORCE VIEW "6.3"("ID", "DATE", "CHECK_IN", "CHECK_OUT", "CLIENT_ID", "ROOM_ID") AS
SELECT * 
FROM "CHECK_";