SELECT ID_PRODUCT_TYPE, ID_PRODUCT, PRICE, 
RANK() OVER(PARTITION BY ID_PRODUCT_TYPE ORDER BY PRICE DESC) AS RNK,
DENSE_RANK() OVER(PARTITION BY ID_PRODUCT_TYPE ORDER BY PRICE DESC) AS DRNK,
(
    SELECT COUNT(PRICE) + 1
    FROM PRODUCT
    WHERE PRICE > P.PRICE
    AND ID_PRODUCT_TYPE = P.ID_PRODUCT_TYPE
) AS NA_RNK,
(
    SELECT COUNT(DISTINCT PRICE) + 1
    FROM PRODUCT
    WHERE PRICE > P.PRICE
    AND ID_PRODUCT_TYPE = P.ID_PRODUCT_TYPE
) AS NA_DRNK
FROM PRODUCT P
ORDER BY P.ID_PRODUCT_TYPE, RNK;



