SELECT ID_PRODUCT, ID_PRODUCT_TYPE, QUANTITY
FROM
(
    SELECT ID_PRODUCT, ID_PRODUCT_TYPE, QUANTITY,
    RANK() OVER (PARTITION BY ID_PRODUCT_TYPE ORDER BY QUANTITY DESC) AS RNK
    FROM
    (
        SELECT PRODUCT.ID_PRODUCT AS ID_PRODUCT,
        ID_PRODUCT_TYPE,
        SUM(QUANTITY) AS QUANTITY
        FROM PRODUCT
        INNER JOIN INVOICE_DETAIL
        ON PRODUCT.ID_PRODUCT = INVOICE_DETAIL.ID_PRODUCT
        GROUP BY ID_PRODUCT_TYPE, PRODUCT.ID_PRODUCT
        ORDER BY ID_PRODUCT_TYPE, ID_PRODUCT
    )
)
WHERE RNK = 1;

SELECT ID_PRODUCT, ID_PRODUCT_TYPE, QUANTITY
FROM
(
    SELECT ID_PRODUCT_TYPE,
    PRODUCT.ID_PRODUCT AS ID_PRODUCT,
    SUM(QUANTITY) AS QUANTITY
    FROM PRODUCT
    INNER JOIN INVOICE_DETAIL
    ON PRODUCT.ID_PRODUCT = INVOICE_DETAIL.ID_PRODUCT
    GROUP BY ID_PRODUCT_TYPE, PRODUCT.ID_PRODUCT
)
INNER JOIN
(
    SELECT ID_PRODUCT_TYPE AS PRODUCT_TYPE, MAX(QUANTITY) AS MAXIMUM
    FROM
    (    
        SELECT PRODUCT.ID_PRODUCT AS ID_PRODUCT,
        ID_PRODUCT_TYPE,
        SUM(QUANTITY) AS QUANTITY
        FROM PRODUCT
        INNER JOIN INVOICE_DETAIL
        ON PRODUCT.ID_PRODUCT = INVOICE_DETAIL.ID_PRODUCT
        GROUP BY ID_PRODUCT_TYPE, PRODUCT.ID_PRODUCT
    )
    GROUP BY ID_PRODUCT_TYPE
)
ON ID_PRODUCT_TYPE = PRODUCT_TYPE AND QUANTITY = MAXIMUM
ORDER BY ID_PRODUCT_TYPE;

