SELECT PRODUCT.ID_PRODUCT, PRODUCT.ID_PRODUCT_TYPE, SUM(PRODUCT.PRICE*INVOICE_DETAIL.QUANTITY) AS SUMMA
FROM PRODUCT
INNER JOIN INVOICE_DETAIL 
ON PRODUCT.ID_PRODUCT = INVOICE_DETAIL.ID_PRODUCT
GROUP BY ROLLUP(PRODUCT.ID_PRODUCT, PRODUCT.ID_PRODUCT_TYPE);

SELECT PRODUCT.ID_PRODUCT, PRODUCT.ID_PRODUCT_TYPE, SUM(PRODUCT.PRICE*INVOICE_DETAIL.QUANTITY) AS SUMMA
FROM PRODUCT
INNER JOIN INVOICE_DETAIL 
ON PRODUCT.ID_PRODUCT = INVOICE_DETAIL.ID_PRODUCT
GROUP BY CUBE(PRODUCT.ID_PRODUCT, PRODUCT.ID_PRODUCT_TYPE);