CREATE OR REPLACE PROCEDURE GET_INVOICE_DETAIL IS
    TEMP NUMBER := 0;

    CURSOR DETAILS IS
    SELECT ID_INVOICE, ID_PRODUCT, QUANTITY 
    FROM INVOICE
    INNER JOIN INVOICE_TARGET ON INVOICE.ID_STUFF = INVOICE_TARGET.ID_STUFF AND INVOICE.INVOICE_DATE = INVOICE_TARGET.PURCHASE_TIME
    INNER JOIN PRODUCT ON PRODUCT.PRODUCT_NAME = FULL_PRODUCT_NAME(INVOICE.SUPPLIER, INVOICE.PRODUCT) AND INVOICE.PRICE = PRODUCT.PRICE;
BEGIN
    FOR DETAIL IN DETAILS
    LOOP
        SELECT COUNT(*) INTO TEMP FROM INVOICE_DETAIL WHERE DETAIL.ID_INVOICE = ID_INVOICE;
        
        IF NOT REGEXP_LIKE(DETAIL.QUANTITY, '^[0-9]+$') THEN
        INSERT INTO ERROR_LOG
        VALUES(ERROR_SEQ.NEXTVAL, CURRENT_DATE, CONCAT('ERROR WITH QUANTITY: ', DETAIL.QUANTITY));
                                       
        ELSIF TEMP > 0 THEN CONTINUE;
        
        ELSE INSERT INTO INVOICE_DETAIL
        VALUES(DETAIL.ID_INVOICE, DETAIL.ID_PRODUCT, DETAIL.QUANTITY, '');
        
        END IF;
    END LOOP;
END GET_INVOICE_DETAIL;



