CREATE OR REPLACE PROCEDURE GET_INVOICE IS
    TEMP NUMBER := 0;

    CURSOR INVOICES IS
    SELECT ID_STUFF, INVOICE_DATE FROM INVOICE;
BEGIN
    FOR INV IN INVOICES
    LOOP
        SELECT COUNT(*) INTO TEMP FROM INVOICE_TARGET WHERE INVOICE_TARGET.ID_STUFF = INV.ID_STUFF
                                                AND INVOICE_TARGET.PURCHASE_TIME = INV.INVOICE_DATE;
                                                
        IF ISDATE(INV.INVOICE_DATE) = 0 THEN
        INSERT INTO ERROR_LOG
        VALUES(ERROR_SEQ.NEXTVAL, CURRENT_DATE, CONCAT('ERROR WITH DATE: ', INV.INVOICE_DATE));
                
        ELSIF TEMP > 0 THEN CONTINUE;
        
        ELSE INSERT INTO INVOICE_TARGET
        VALUES(INVOICE_SEQ.NEXTVAL, 1, INV.ID_STUFF, INV.INVOICE_DATE);
        
        END IF;
    END LOOP;
END GET_INVOICE;


