CREATE OR REPLACE PROCEDURE GET_PRODUCT IS
    TEMP NUMBER := 0;
    SUPP NUMBER;

    CURSOR PRODUCTS IS
    SELECT SUPPLIER, PRODUCT, PRICE FROM INVOICE;
BEGIN
    FOR PROD IN PRODUCTS
    LOOP
        SELECT COUNT(*) INTO TEMP FROM PRODUCT WHERE PRODUCT.PRODUCT_NAME = FULL_PRODUCT_NAME(PROD.SUPPLIER, PROD.PRODUCT)
                                                AND PRODUCT.PRICE = PROD.PRICE;
                                                
        SELECT COUNT(*) INTO SUPP FROM SUPPLIER WHERE SUPPLIER.SUPPLIER_NAME = PROD.SUPPLIER;
        IF SUPP = 0 THEN CONTINUE;
        END IF;
        
        SELECT ID_SUPPLIER INTO SUPP FROM SUPPLIER WHERE SUPPLIER.SUPPLIER_NAME = PROD.SUPPLIER;

        IF NOT REGEXP_LIKE(PROD.PRODUCT, '^TV-[0-9]+$') OR PROD.PRODUCT IS NULL THEN
        INSERT INTO ERROR_LOG
        VALUES(ERROR_SEQ.NEXTVAL, CURRENT_DATE, CONCAT('ERROR WITH PRODUCT: ', PROD.PRODUCT));
                
        ELSIF TEMP > 0 THEN CONTINUE;
        
        ELSE INSERT INTO PRODUCT
        VALUES(PRODUCT_SEQ.NEXTVAL, 1, SUPP, 1, FULL_PRODUCT_NAME(PROD.SUPPLIER, PROD.PRODUCT), '', PROD.PRICE);
        
        END IF;
    END LOOP;
END GET_PRODUCT;

