CREATE OR REPLACE FUNCTION GET_FIRST_NAME (STR IN VARCHAR2) RETURN VARCHAR2 AS 
BEGIN
    RETURN SUBSTR(STR, 1, INSTR(STR, ' ')-1);
END GET_FIRST_NAME;

CREATE OR REPLACE FUNCTION GET_LAST_NAME (STR IN VARCHAR2) RETURN VARCHAR2 AS 
BEGIN
    RETURN SUBSTR(STR, INSTR(STR, ' ')+1, LENGTH(STR)-INSTR(STR, ' '));
END GET_LAST_NAME;

CREATE OR REPLACE FUNCTION GENERATE_PHONE_NUMBER RETURN VARCHAR2 AS
BEGIN
    RETURN CONCAT('+380', ROUND(DBMS_RANDOM.VALUE(100000000,999999999)));
END GENERATE_PHONE_NUMBER;

CREATE OR REPLACE FUNCTION GENERATE_ADDRESS RETURN VARCHAR2 AS
BEGIN
    RETURN CONCAT(ROUND(DBMS_RANDOM.VALUE(1,100)), ' AVE, NEW-YORK');
END GENERATE_ADDRESS;

CREATE OR REPLACE FUNCTION FULL_PRODUCT_NAME (SUPP IN VARCHAR2, PROD IN VARCHAR2) RETURN VARCHAR2 AS
BEGIN
    RETURN CONCAT(SUPP, CONCAT(' ', PROD));
END FULL_PRODUCT_NAME;

CREATE OR REPLACE FUNCTION INVOICE_NUMBER(INVOICE_NUM IN VARCHAR2) RETURN VARCHAR2 AS
BEGIN 
    RETURN SUBSTR(INVOICE_NUM, INSTR(INVOICE_NUM, '-')+1, LENGTH(INVOICE_NUM)-INSTR(INVOICE_NUM, '-'));
END INVOICE_NUMBER;

CREATE OR REPLACE FUNCTION ISDATE(STR IN VARCHAR2) RETURN NUMBER AS
    TEMP DATE;
BEGIN
    SELECT TO_DATE(STR, 'DD-MM-YY') INTO TEMP FROM DUAL;
    RETURN 1;
    
    EXCEPTION WHEN OTHERS THEN
    RETURN 0;
END;

